#PBS -lselect=1:ncpus=10:mem=100gb
#PBS -lwalltime=00:30:00
## Load system modules
module load vtk/5.8.0 
module load mpi/intel-2019.8.254 # This is prefered over the default 2019
module load boost/1.72.0
module load petsc/3.3-p3-intel-11

cd $HOME/LeachingSim
mpiexec -n 10 ./release/LeachingSim_uint8 \
       --raw-file LA3_d0_v1_uint8_unnormalised_338_338_283.raw \
       --xext 338 \
       --yext 338 \
       --zext 283 \
       --dt 0.1 \
       --tmax 10.0 \
       --nout 1 \
       --kreac 1000 \
       --out_dir ./simulation_output