#PBS -lselect=2:ncpus=64:mem=100gb
#PBS -lwalltime=48:00:00

module load tools/prod
module load foss/2023a
module load Boost/1.82.0-GCC-12.3.0
module load PETSc/3.20.3-foss-2023a
module load VTK/9.3.0-foss-2023a

cd $HOME/LeachingSim
mpiexec ./release/LeachingSim_uint8 \
       --raw-file LA3_d0_v1_uint8_unnormalised_338_338_283.raw \
       --xext 338 \
       --yext 338 \
       --zext 283 \
       --dt 0.005 \
       --tmax 10000.0 \
       --nout 10 \
       --D 0.0000001 \
       --kreac 1000 \
       --voxel_size 0.000017 \
       --out_dir ./simulation_output
