#PBS -lselect=2:ncpus=64:mem=100gb
#PBS -lwalltime=48:00:00
#PBS -j oe
#PBS -N time_based_LeachingSim_Job

module load tools/prod
module load foss/2023a
module load Boost/1.82.0-GCC-12.3.0
module load PETSc/3.20.3-foss-2023a
module load VTK/9.3.0-foss-2023a

cd $EPHEMERAL/LeachingSim

echo "Job running on nodes:"
cat $PBS_NODEFILE

# Run MPI with error redirection
# 2>&1 redirects stderr (2) to stdout (1), so both go into the log file.
# Preconditioners:
# -pc_type bjacobi -sub_pc_type ilu
# -pc_type hypre -pc_hypre_type boomeramg
# Monitors
# -press_ksp_monitor \
# -press_ksp_converged_reason \

# Dump vtk files using fixed number of iterations --nout
#stdbuf -oL -eL mpiexec -n 128 --oversubscribe ./release/LeachingSim_uint8 \
#       --raw-file LA3_d0_v1_uint8_unnormalised_338_338_283.raw \
#       --xext 338 \
#       --yext 338 \
#       --zext 283 \
#       --csat 1.0 \
#       --theta 1.0 \
#       --dt 3600.0 \
#       --tmax 1728000.0 \
#       --nout 100 \
#       --D 0.0000001 \
#       --kreac 1000 \
#       --voxel_size 0.000017 \
#       --top_pressure 10.0 \
#       --evap_flux 0.0 \
#       --implicit_sat true \
#       --debug true \
#       --out_dir ./agglomerate_leaching_test_output \
#       -press_pc_type hypre \
#       -press_pc_hypre_type boomeramg \
#       -sat_pc_type bjacobi \
#       -sat_sub_pc_type ilu \
#       -conc_pc_type bjacobi \
#       -conc_sub_pc_type ilu \
#       -acid_pc_type bjacobi \
#       -acid_sub_pc_type ilu \
#       > agglomerate_leaching_test_log 2>&1

# Dump vtk files using fixed out time every physical hour
#--use_out_time true \
#--out_time 3600.0 \
stdbuf -oL -eL mpiexec -n 128 --oversubscribe ./release/LeachingSim_uint8 \
       --raw-file LA3_d0_v1_uint8_CLEANED_338_338_283.raw \
       --xext 338 \
       --yext 338 \
       --zext 283 \
       --csat 1.0 \
       --theta 1.0 \
       --dt 3600.0 \
       --tmax 1728000.0 \
       --use_out_time true \
       --out_time 3600.0 \
       --D 0.0000001 \
       --kreac 1000 \
       --voxel_size 0.000017 \
       --top_pressure 10.0 \
       --evap_flux 0.0 \
       --implicit_sat true \
       --debug true \
       --time_scalar 1000.0 \
       --enable_microporosity true \
       --rock_D_fac 0.001 \
       --out_dir ./time_based_agglomerate_leaching_test_output \
       -press_pc_type hypre \
       -press_pc_hypre_type boomeramg \
       -sat_pc_type bjacobi \
       -sat_sub_pc_type ilu \
       -sat_sub_pc_factor_shift_type NONZERO \
       -conc_pc_type bjacobi \
       -conc_sub_pc_type ilu \
       -conc_sub_pc_factor_shift_type NONZERO \
       -acid_pc_type bjacobi \
       -acid_sub_pc_type ilu \
       -acid_sub_pc_factor_shift_type NONZERO \
       > time_based_agglomerate_leaching_test_log 2>&1