#PBS -lselect=1:ncpus=10:mem=100gb
#PBS -lwalltime=00:30:00
#PBS -j oe
#PBS -N short_test

module load tools/prod
module load foss/2023a
module load Boost/1.82.0-GCC-12.3.0
module load PETSc/3.20.3-foss-2023a
module load VTK/9.3.0-foss-2023a

cd $EPHEMERAL/LeachingSim

# Optional: Generate the input file first (Requires loading python and a venv with Numpy)
# eval "$(~/miniforge3/bin/conda shell.bash hook)"
# conda activate general_venv
# python generate_input.py

echo "Job running on nodes:"
cat $PBS_NODEFILE

# Parameters for the short test:
# dx = 1e-4 m
# D  = 1e-9 m^2/s
# Stability limit: dt < dx^2 / (2*D) = 5.0s. We use dt=1.0s.

# Simluation cases can vary depending on some options values, e.g.
#       Leaching case
#		./LeachingSim --top_pressure 10000.0 --evap_flux 0.0 ... 
#		The material is "irrigated" keeping it wet. Evaporation is negligible.
#	Drying case
#		./LeachingSim --top_pressure 0.0 --evap_flux 1.0e-6 ...
#		There is no downward push. 
#		Evaporation pulls liquid volume out of the surface-connected pores and surface pores are converted into solid

# Preconditioners:
# -pc_type bjacobi -sub_pc_type ilu -> FAILS!
# -pc_type hypre -pc_hypre_type boomeramg
# Using prefix for KSP options
# -press_pc_type hypre -press_pc_hypre_type boomeramg
#      > checkpoint_leaching_test.log 2>&1

# We use 'stdbuf -oL -eL' to force the OS to write to the log line-by-line immediately
stdbuf -oL -eL mpiexec -n 10 --oversubscribe ./release/LeachingSim_uint8 \
       --raw-file channel_test_input.raw \
       --xext 50 \
       --yext 50 \
       --zext 50 \
       --csat 1.0 \
       --theta 1.0 \
       --dt 3600.0 \
       --tmax 864000.0 \
       --use_out_time true \
       --out_time 3600.0 \
       --D 1.0 \
       --kreac 1.0e-4 \
       --voxel_size 1.0 \
       --top_pressure 10000 \
       --evap_flux 0.0 \
       --chk_freq 50 \
       --implicit_sat true \
       --debug true \
       --time_scalar 1000.0 \
       --enable_microporosity true \
       --rock_D_fac 0.001 \
       --out_dir ./preconditioner_leaching_test_output \
       -press_pc_type hypre \
       -press_pc_hypre_type boomeramg \
       -sat_pc_type jacobi \
       -conc_pc_type jacobi \
       -acid_pc_type jacobi \
       -press_ksp_monitor \
       -press_ksp_converged_reason \
       > preconditioner_leaching_test.log 2>&1

#mpiexec -n 10 --oversubscribe ./release/LeachingSim_uint8 \
#       --raw-file channel_test_input.raw \
#       --xext 50 \
#       --yext 50 \
#       --zext 50 \
#       --csat 1.0 \
#       --theta 1.0 \
#       --dt 3600.0 \
#       --tmax 864000.0 \
#       --nout 1 \
#       --D 1.0 \
#       --kreac 1.0e-4 \
#       --voxel_size 1.0 \
#       --top_pressure 10000 \
#       --evap_flux 0.0 \
#       --chk_freq 50 \
#       --implicit_sat true \
#       --debug true \
#       --out_dir ./preconditioner_leaching_test_output \
#       -press_pc_type hypre \
#       -press_pc_hypre_type boomeramg \
#       -press_ksp_view \
#       > preconditioner_leaching_test.log 2>&1