#PBS -lselect=1:ncpus=10:mem=100gb
#PBS -lwalltime=00:30:00
#PBS -j oe
#PBS -N short_test

module load tools/prod
module load foss/2023a
module load Boost/1.82.0-GCC-12.3.0
module load PETSc/3.20.3-foss-2023a
module load VTK/9.3.0-foss-2023a

cd $EPHEMERAL/LeachingSim

# Optional: Generate the input file first (Requires loading python and a venv with Numpy)
# eval "$(~/miniforge3/bin/conda shell.bash hook)"
# conda activate general_venv
# python generate_input.py

echo "Job running on nodes:"
cat $PBS_NODEFILE

# Parameters for the short test:
# dx = 1e-4 m
# D  = 1e-9 m^2/s
# Stability limit: dt < dx^2 / (2*D) = 5.0s. We use dt=1.0s.

# Simluation cases can vary depending on some options values, e.g.
#       Leaching case
#		./LeachingSim --top_pressure 10000.0 --evap_flux 0.0 ... 
#		The material is "irrigated" keeping it wet. Evaporation is negligible.
#	Drying case
#		./LeachingSim --top_pressure 0.0 --evap_flux 1.0e-6 ...
#		There is no downward push. 
#		Evaporation pulls liquid volume out of the surface-connected pores and surface pores are converted into solid

mpiexec -n 10 --oversubscribe ./release/LeachingSim_uint8 \
       --raw-file channel_test_input.raw \
       --xext 50 \
       --yext 50 \
       --zext 50 \
       --csat 1.0 \
       --theta 1.0 \
       --dt 3600.0 \
       --tmax 864000.0 \
       --nout 1 \
       --D 1.0 \
       --kreac 1.0e-4 \
       --voxel_size 1.0 \
       --top_pressure 0.0 \
       --evap_flux 1.0e-6 \
       --out_dir ./curing_test_output \
       > curing_test.log 2>&1